packages:
  - frontend

nodeLinker: hoisted

overrides:
  "@electron/packager": 20.3.0
  "@electron/rebuild@3.7.2>@electron/node-gyp": 10.2.0-electron.2
  js-yaml: 4.3.1
  nanoid: 3.3.18
  tar: 7.5.21
  tmp: 0.2.7

patchedDependencies:
  "@electron-forge/core@7.11.2": patches/@electron-forge__core@7.11.2.patch

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true

verifyDepsBeforeRun: warn
enableGlobalVirtualStore: false
